### ISSUE TITLE
zte h298n router

### ISSUE THREAD

**Issue by phairplay** [kadima-tech/experia-v10-device-tracker#1]
hi,
i've just changed internet provider and they say my new router will be zte h298n while looking to see if it will work with HA i came across your github page.

do you know if this will work with my router?

**Comment by sjaakiejj** [comment]
Hey Phairplay,

Considering the router is a different model I would say it's fairly unlikely that this will work for your new router. There's a small off chance that the routers share the same interface though.

If you try it, please also update this issue with the results. That way others with the same question will be helped as well.
