### ISSUE TITLE
Devices not visible when using an Access Point

### ISSUE THREAD

**Issue by wiebeww** [kadima-tech/experia-v10-device-tracker#7]
Hi,

Only the devices that are shown are connected by Wifi are visible in the 'known devices' file.
I am using an router/ap, so my wireless devices are shown on the Experiabox as wired (LAN) instead of Wireless.

Is it possible to track the wired devices?

Kind regards,

Wiebe

**Comment by sjaakiejj** [comment]
Hi Wiebeww,

The problem with the router showing the devices connected via the access point as wired is that the router doesn't update the list frequently. This makes the LAN devices (even though they're connected through an access point) impossible to track from the Experiabox. 

I think your best option would be to add a second device tracker specifically for your access point.

**Comment by robinvalk** [comment]
Does this repo also support the Experia Wifi access points by KPN?
