### ISSUE TITLE
HA version 0.99.3

### ISSUE THREAD

**Issue by MaVeWeb** [kadima-tech/experia-v10-device-tracker#9]
Since HA version 0.99.3, it appears that the experia v10 device tracker is not working any more.    The state stays at: not_home.

Are more users expericing this issue? 

Update: I noticed that the firmware of the experience box was updated to: firmware V10 T03.7. May this update be responsible for this issue?

**Comment by Cadsters** [comment]
I am experiencing the same. Can not track back what caused it.

**Comment by Erikkyw** [comment]
same problem here

**Comment by Wouter0100** [comment]
Should be fixed in #10. Works on my experiabox again :). They've updated the login logic a bit.
